In [1]:
import numpy as np

In [3]:
# column vector
c = np.array([1,2,3])
print(c.shape)
print(c[0])

(3,)
1


In [5]:
# row vector
c = np.array([[1,2,3]])
print(c.shape)

(1, 3)


In [6]:
# obtaining a particular entry
print(c[0,1])
# 첫번째 row의 두번째 column.

2


In [7]:
a = np.zeros((2,2))
b = np.ones((3,3))
print(a)
print(b)

c = np.full((2,2),4)
print(c)
d = np.random.random((2,2))
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]]
[[0.83760198 0.74843859]
 [0.8251961  0.93437875]]


In [18]:
A = np.array([[1,2],[2,3]])
print(A)

[[1 2]
 [2 3]]


In [19]:
# transpose
A.T

array([[1, 2],
       [2, 3]])

In [20]:
# matrix multiplication
np.dot(A,A.T)

array([[ 5,  8],
       [ 8, 13]])

In [21]:
# identity matrix
eye3 = np.eye(3)
print(eye3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
# 역행렬 계산하기
from numpy.linalg import inv
A_inv = inv(A)
print(A_inv)

[[-3.  2.]
 [ 2. -1.]]


In [25]:
x = A_inv.dot(A)
x

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Ax = b 형태의 행렬식에서 x를 빠르게 구하는 방법
from numpy.linalg import solve
k = solve(A,b)
## 형태로 값을 구할 수 있다.
## 역행렬을 직접 구해야 하는 경우는 거의 없다. 대부분 역행렬 연산이 정답을 구하는 과정에서 등장할 뿐임.
## 오히려 numerical stability의 문제 때문에 역행렬을 직접 구하지 않는다고 함. 
# solve 함수도 내부적으로는 역행렬 연산을 쓰지 않는다.