In [1]:
import numpy as np
import numpy.linalg as la
from numpy.linalg import eig # eigenvector / eigenvalue를 반환하는 함수
from numpy.linalg import inv

import time

In [2]:
# diagonalization and power of a matrix 
# 3 by 3
A = np.array([[4, 0, -2], [2, 5, 4], [0, 0, 5]])
A

array([[ 4,  0, -2],
       [ 2,  5,  4],
       [ 0,  0,  5]])

In [3]:
eig_val, eig_vec = eig(A)

In [4]:
eig_val

array([5., 4., 5.])

In [5]:
eig_vec

array([[ 0.        ,  0.4472136 , -0.89442719],
       [ 1.        , -0.89442719,  0.        ],
       [ 0.        ,  0.        ,  0.4472136 ]])

eigenvalue 5에 대응되는 eigenvector가 [0,1,0] 으로 첫번째 col.

4에 대응되는 건 두번째 col.... 로 해석하면 된다.

In [6]:
D = np.diag(eig_val) # 주어진 matrix를 대각화.
D

array([[5., 0., 0.],
       [0., 4., 0.],
       [0., 0., 5.]])

In [7]:
V = eig_vec
V

array([[ 0.        ,  0.4472136 , -0.89442719],
       [ 1.        , -0.89442719,  0.        ],
       [ 0.        ,  0.        ,  0.4472136 ]])

In [8]:
V.dot(D).dot(la.inv(V))

array([[ 4.,  0., -2.],
       [ 2.,  5.,  4.],
       [ 0.,  0.,  5.]])

In [9]:
la.matrix_power(A,5) # 동일한 매트릭스를 5번 곱한 결과.

array([[ 1024,     0, -4202],
       [ 4202,  3125,  8404],
       [    0,     0,  3125]])

In [11]:
D_power_5 = np.diag(eig_val**5) # 각 value만 다섯 번 거듭제곱. 고유값 변환을 위한 출발점.
D_power_5

array([[3125.,    0.,    0.],
       [   0., 1024.,    0.],
       [   0.,    0., 3125.]])

In [12]:
V.dot(D_power_5).dot(la.inv(V)) # A를 다섯 번 곱한 것과 동일한 결과 출력.

array([[ 1024.,     0., -4202.],
       [ 4202.,  3125.,  8404.],
       [    0.,     0.,  3125.]])

In [15]:
# 곱셉을 여러 번 했을 때, 곧이곧대로 A 곱한 것보다 빠르다는 걸 보여준 예제.

# create a matrix A
A = np.array([[4., 4, 2, 3, -2], [0, 1, -2, -2, 2], [6, 12, 11, 2, -4], [9, 20, 10, 10, -6], [15, 28, 14, 5, -3]])

A = A + A.T
# 랜덤으로 행렬을 만들 때, 그 행렬이 반드시 linear independent하다는 보장은 할 수 없음
# 그래서 몇 가지 전처리 작업을 거친 것. 이런 전처리 작업을 거치면 eigenDecomposition이 가능하도록 보장한다고 함.
A = A/np.expand_dims(np.sum(A, 1), axis = 1)
print (A)


# initialize parameters
x = np.random.rand(5)
n_times = 1000000

# perform matrix multiplications
y = x
start_time = time.time()
for i in range(0, n_times):
    y = A.dot(y)
end_time = time.time()
elapse_time = end_time - start_time
print (y)
print (elapse_time)

[[ 0.17777778  0.08888889  0.17777778  0.26666667  0.28888889]
 [ 0.0625      0.03125     0.15625     0.28125     0.46875   ]
 [ 0.12903226  0.16129032  0.35483871  0.19354839  0.16129032]
 [ 0.19672131  0.29508197  0.19672131  0.32786885 -0.01639344]
 [ 0.2826087   0.65217391  0.2173913  -0.02173913 -0.13043478]]
[0.48035952 0.48035952 0.48035952 0.48035952 0.48035952]
0.5170638561248779


In [16]:
eig_val, eig_vec = eig(A)
D = np.diag(eig_val)
V = eig_vec

# perform matrix multiplications using eigendecomposition
start_time = time.time()
y = V.dot((eig_val**n_times)*la.solve(V,x)) # V.dot(a) = x 인 a를 구한 것.
# (inverse를 직접 연산한 게 아니라 그냥 답만 찾은 셈. 이게 더 안정적이라고.)
# diagnal matrix를 만들어서 곱한 게 아니라, vector인 채로 element 곱셈을 진행했다고 함.
end_time = time.time()
elapse_time = end_time - start_time
print (y)
print (elapse_time)

[0.48035952 0.48035952 0.48035952 0.48035952 0.48035952]
0.00013494491577148438
